# Generated by Django 3.0.1 on 2020-03-01 18:45

import ZilanCMS.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, verbose_name='类型名称')),
                ('num', models.PositiveIntegerField(default=5, verbose_name='加载文章数量')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, verbose_name='类型名称')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='电话')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('shot', models.CharField(max_length=300, null=True, verbose_name='头像')),
                ('is_expand', models.BooleanField(default=False, verbose_name='是否为扩展账户')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否为付费账户')),
                ('is_manager', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为超级管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WebSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='网站标题')),
                ('nick_name', models.CharField(max_length=200, verbose_name='网站别名')),
                ('verify_api', models.CharField(max_length=300, verbose_name='api验证串')),
                ('extend', models.TextField(verbose_name='扩展说明(百度验证等)')),
                ('mobile_logo', models.ImageField(default='common/m_logo.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='手机网站logo')),
                ('logo', models.ImageField(default='common/logo.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='网站logo')),
                ('backstage_logo', models.ImageField(default='common/b_logo.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='后台logo')),
                ('backstage_login_logo', models.ImageField(default='common/l_logo.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='后台登录logo')),
                ('hittimes', models.IntegerField(default=0, verbose_name='阅读量')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否开放')),
                ('close_note', models.CharField(max_length=200, verbose_name='关闭说明')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('tpl_style', models.CharField(default='default', max_length=200, verbose_name='模板风格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webset', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='作品名称')),
                ('file_illustrate', models.TextField(verbose_name='作品说明')),
                ('operate_illustrate', models.TextField(verbose_name='操作说明')),
                ('location', models.FileField(upload_to=ZilanCMS.models.user_directory_path, verbose_name='文件存储位置')),
                ('thumbnail', models.ImageField(default='common/thumbnail.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='缩略图片位置')),
                ('hittimes', models.IntegerField(default=0, verbose_name='点击数')),
                ('thumbup', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_charge', models.BooleanField(default=False, verbose_name='是否收费')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZilanCMS.FileType', verbose_name='类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadwork', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200, verbose_name='名称')),
                ('port', models.IntegerField(default=25, verbose_name='端口')),
                ('account', models.CharField(max_length=200, verbose_name='账户')),
                ('password', models.CharField(max_length=200, verbose_name='账户密码')),
                ('poster', models.CharField(max_length=200, verbose_name='发件人姓名')),
                ('mail', models.CharField(max_length=200, verbose_name='邮箱地址')),
                ('encoded', models.CharField(default='UTF-8', max_length=20, verbose_name='邮件编码')),
                ('is_ssl', models.BooleanField(default=False, verbose_name='是否启用ssl')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stmp', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.ImageField(upload_to=ZilanCMS.models.user_directory_path, verbose_name='文件存储位置')),
                ('thumbnail', models.ImageField(default='common/thumbnail.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='缩略图片位置')),
                ('hittimes', models.IntegerField(default=0, verbose_name='阅读量')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-sort'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.CharField(max_length=300, verbose_name='链接地址')),
                ('logo', models.ImageField(default='common/thumbnail.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='logo')),
                ('hittimes', models.IntegerField(default=0, verbose_name='阅读量')),
                ('thumbup', models.IntegerField(default=0, verbose_name='点赞数')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-sort'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='导航标题')),
                ('tag', models.CharField(max_length=30, verbose_name='导航标志字符串')),
                ('url', models.CharField(max_length=300, verbose_name='导航条外部链接')),
                ('hittimes', models.IntegerField(default=0, verbose_name='点击量')),
                ('article_num', models.PositiveIntegerField(default=5, verbose_name='加载文章数量')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZilanCMS.ArticleType', verbose_name='加载文章类别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-sort'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Meessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='留言标题')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('username', models.CharField(max_length=200, verbose_name='留言者姓名')),
                ('phone', models.CharField(max_length=200, verbose_name='留言者电话')),
                ('hittimes', models.IntegerField(default=0, verbose_name='阅读量')),
                ('thumbup', models.IntegerField(default=0, verbose_name='点赞数')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-sort'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaseArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('title2', models.CharField(max_length=300, verbose_name='文章副标题')),
                ('note', models.TextField(verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('enclosure', models.FileField(upload_to=ZilanCMS.models.user_directory_path, verbose_name='文件存储位置')),
                ('thumbnail', models.ImageField(default='common/thumbnail.jpg', upload_to=ZilanCMS.models.user_directory_path, verbose_name='缩略图片位置')),
                ('hittimes', models.IntegerField(default=0, verbose_name='阅读量')),
                ('thumbup', models.IntegerField(default=0, verbose_name='点赞数')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_delated', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZilanCMS.ArticleType', verbose_name='文章类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-sort'],
                'managed': True,
            },
        ),
    ]
