# Generated by Django 3.0.1 on 2020-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0002_alluser_is_disuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='is_delated',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
