# Generated by Django 3.0.1 on 2020-03-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0003_alluser_is_delated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluser',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='basearticle',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='meessage',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='stmp',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='uploadwork',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='webset',
            old_name='is_delated',
            new_name='is_deleted',
        ),
    ]
