# Generated by Django 3.0.1 on 2020-03-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0004_auto_20200306_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, verbose_name='类型名称')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='url',
        ),
        migrations.AddField(
            model_name='alluser',
            name='company',
            field=models.CharField(max_length=100, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='basearticle',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='链接地址'),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='链接地址'),
        ),
        migrations.AddField(
            model_name='picture',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='phone',
            field=models.CharField(default=13333333333, max_length=11, unique=True, verbose_name='电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alluser',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZilanCMS.UserType', verbose_name='组别'),
        ),
    ]
