# Generated by Django 3.0.1 on 2020-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0005_auto_20200307_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ZilanCMS.UserType', verbose_name='组别'),
            preserve_default=False,
        ),
    ]
