# Generated by Django 3.0.1 on 2020-03-08 23:21

import ZilanCMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0008_auto_20200308_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basearticle',
            name='thumbnail',
            field=models.ImageField(default='common/thumbnail.jpg', null=True, upload_to=ZilanCMS.models.user_directory_path, verbose_name='缩略图片位置'),
        ),
    ]
