# Generated by Django 3.0.1 on 2020-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0009_auto_20200308_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
