# Generated by Django 3.0.1 on 2020-03-09 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ZilanCMS', '0010_articletype_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='tag',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='标志字符串'),
            preserve_default=False,
        ),
    ]
